version: '3.9'

services:
  
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: mongodb://root:example@db:27017/members

  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example